aplicacion:
  nombre: Mis Juegos api
   
server:
  port: ${PORT:9083}
  servlet:
    context-path: /misjuegos
  
spring:
  data:
    mongodb:
      uri: mongodb+srv://davidof1977:baralo18@davidof1977.4gzm1.mongodb.net/mis-juegos?retryWrites=true&w=majority